//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace MediaChromeService
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MediaChromeEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MediaChromeEntities object using the connection string found in the 'MediaChromeEntities' section of the application configuration file.
        /// </summary>
        public MediaChromeEntities() : base("name=MediaChromeEntities", "MediaChromeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MediaChromeEntities object.
        /// </summary>
        public MediaChromeEntities(string connectionString) : base(connectionString, "MediaChromeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MediaChromeEntities object.
        /// </summary>
        public MediaChromeEntities(EntityConnection connection) : base(connection, "MediaChromeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<playlist> playlist
        {
            get
            {
                if ((_playlist == null))
                {
                    _playlist = base.CreateObjectSet<playlist>("playlist");
                }
                return _playlist;
            }
        }
        private ObjectSet<playlist> _playlist;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the playlist EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToplaylist(playlist playlist)
        {
            base.AddObject("playlist", playlist);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MediaChromeModel", Name="playlist")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class playlist : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new playlist object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="title">Initial value of the title property.</param>
        /// <param name="userID">Initial value of the userID property.</param>
        /// <param name="collaborative">Initial value of the collaborative property.</param>
        public static playlist Createplaylist(global::System.Int32 id, global::System.String title, global::System.Int32 userID, global::System.Byte collaborative)
        {
            playlist playlist = new playlist();
            playlist.id = id;
            playlist.title = title;
            playlist.userID = userID;
            playlist.collaborative = collaborative;
            return playlist;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userID
        {
            get
            {
                return _userID;
            }
            set
            {
                OnuserIDChanging(value);
                ReportPropertyChanging("userID");
                _userID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userID");
                OnuserIDChanged();
            }
        }
        private global::System.Int32 _userID;
        partial void OnuserIDChanging(global::System.Int32 value);
        partial void OnuserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String songs
        {
            get
            {
                return _songs;
            }
            set
            {
                OnsongsChanging(value);
                ReportPropertyChanging("songs");
                _songs = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("songs");
                OnsongsChanged();
            }
        }
        private global::System.String _songs;
        partial void OnsongsChanging(global::System.String value);
        partial void OnsongsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte collaborative
        {
            get
            {
                return _collaborative;
            }
            set
            {
                OncollaborativeChanging(value);
                ReportPropertyChanging("collaborative");
                _collaborative = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("collaborative");
                OncollaborativeChanged();
            }
        }
        private global::System.Byte _collaborative;
        partial void OncollaborativeChanging(global::System.Byte value);
        partial void OncollaborativeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String annotation
        {
            get
            {
                return _annotation;
            }
            set
            {
                OnannotationChanging(value);
                ReportPropertyChanging("annotation");
                _annotation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("annotation");
                OnannotationChanged();
            }
        }
        private global::System.String _annotation;
        partial void OnannotationChanging(global::System.String value);
        partial void OnannotationChanged();

        #endregion
    
    }

    #endregion
    
}
