//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:2.0.50727.3615
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpofityRuntime.Properties {
	using System;
	
	
	/// <summary>
	///   En resursklass med strikt typkontroll för uppslag av lokaliserade strängar o.s.v.
	/// </summary>
	// Denna klass har automatgenererats av klassen StronglyTypedResourceBuilder
	// via ett verktyg, till exempel ResGen eller Visual Studio.
	// Om du vill lägga till eller ta bort en medlem ändrar du i ResX-filen och kör ResGen
	// igen med växeln /str, eller bygger om VS-projektet
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Returnerar den cachelagrade ResourceManager-instans som den här klassen använder.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpofityRuntime.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Ersätter den aktuella trådens egenskap CurrentUICulture för alla
		///   resursuppslag med denna resursklass (strikt typkontroll).
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		internal static System.Drawing.Bitmap ajax_loader {
			get {
				object obj = ResourceManager.GetObject("ajax-loader", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap back {
			get {
				object obj = ResourceManager.GetObject("back", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap button1 {
			get {
				object obj = ResourceManager.GetObject("button1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap button2 {
			get {
				object obj = ResourceManager.GetObject("button2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap forward {
			get {
				object obj = ResourceManager.GetObject("forward", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap kan1 {
			get {
				object obj = ResourceManager.GetObject("kan1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap kan2 {
			get {
				object obj = ResourceManager.GetObject("kan2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap pause {
			get {
				object obj = ResourceManager.GetObject("pause", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap play {
			get {
				object obj = ResourceManager.GetObject("play", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap searchbtn {
			get {
				object obj = ResourceManager.GetObject("searchbtn", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap searchfield {
			get {
				object obj = ResourceManager.GetObject("searchfield", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap searchfield2 {
			get {
				object obj = ResourceManager.GetObject("searchfield2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap searchfield3 {
			get {
				object obj = ResourceManager.GetObject("searchfield3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap spotify_core_logo_128x128 {
			get {
				object obj = ResourceManager.GetObject("spotify-core-logo-128x128", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap stop {
			get {
				object obj = ResourceManager.GetObject("stop", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Slår upp en lokaliserad sträng som liknar body
		///{
		///background-color:#484848;
		///color:#AAAAAA;
		///text-shadow:2px 2px #000000;
		///font-size:8px;
		///}
		///img
		///{
		///-moz-box-shadow: 1px 1px 1px #000000;
		///border: 1px solid #000000;
		///}
		///.
		/// </summary>
		internal static string StyleSheet {
			get {
				return ResourceManager.GetString("StyleSheet", resourceCulture);
			}
		}
		
		internal static System.Drawing.Bitmap update {
			get {
				object obj = ResourceManager.GetObject("update", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
